name: autotestingui
description: A universal automation and UI overflow detection tool for Flutter.
version: 0.0.1
homepage: https://github.com/yourusername/AutoTestingUI
repository: https://github.com/yourusername/AutoTestingUI
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
